SELECT
 TAB.CODTAB,
 EXC.CODPROD,
 EXC.VLRVENDA,
 EXC.NUTAB
FROM TGFTAB TAB
INNER JOIN TGFEXC EXC ON EXC.NUTAB = TAB.NUTAB

WHERE TAB.CODTAB = :CODTAB
  AND EXC.CODPROD = :CODPROD
  AND TAB.NUTAB = (SELECT MAX(T.NUTAB) FROM TGFTAB T
                 INNER JOIN TGFEXC E ON E.NUTAB = T.NUTAB
                 WHERE T.CODTAB = TAB.CODTAB
                   AND E.CODPROD = EXC.CODPROD
                   AND T.DTVIGOR <= TRUNC(:DTMOV))