SELECT
    NVL(MODEMP.NUNOTA,MODTPO.NUNOTA) NUNOTAMOD
FROM TSIPAR PAR
         INNER JOIN AD_BHZGESMODTPO MODTPO ON MODTPO.CODTIPOPER = PAR.INTEIRO
         LEFT JOIN AD_BHZGESMODEMP MODEMP ON MODEMP.CODIGO = MODTPO.CODIGO AND MODEMP.CODEMP = :CODEMP AND MODEMP.NUNOTA IS NOT NULL

WHERE PAR.CHAVE = 'BHZTPOINFUSO'
  AND PAR.CODUSU = 0