SELECT
    MOV.SEQ,
    MOV.DESCRICAO,
    NVL(MOV.CODTIPOPERORIG,0) CODTIPOPERORIG,
    NVL(MOV.CODTIPOPERDEST,0) CODTIPOPERDEST,
    NVL(MOV.CODLOCALORIG,0) CODLOCALORIG,
    NVL(MOV.CODLOCALDEST,0) CODLOCALDEST,
    NVL(MOV.TIPMOVAUTO,0) TIPMOVAUTO,
    NVL(MOV.ORDEM,MOV.SEQ) ORDEM,
    NVL(MOV.GERACONF,'N') GERACONF,
    NVL(MOV.GERAVINCORIG,'N') GERAVINCORIG,
    NVL(MODEMP.NUNOTA,MODTPO.NUNOTA) NUNOTAMOD
FROM TGFCAB CAB
         INNER JOIN AD_BHZAUTOMOV MOV ON MOV.CODTIPOPERORIG = CAB.CODTIPOPER AND NULLVALUE(MOV.MOVBOTACAO,'N') = 'S'
         INNER JOIN AD_BHZGESMODTPO MODTPO ON MODTPO.CODTIPOPER = MOV.CODTIPOPERDEST
         LEFT JOIN AD_BHZGESMODEMP MODEMP ON MODEMP.CODIGO = MODTPO.CODIGO AND MODEMP.CODEMP = CAB.CODEMP AND MODEMP.NUNOTA IS NOT NULL

WHERE CAB.NUNOTA = :NUNOTA

ORDER BY NVL(ORDEM,MOV.SEQ)