WITH RETREM AS (
    SELECT
        IREM.NUNOTA NUNOTAREM,
        IREM.SEQUENCIA SEQUENCIAREM,
        IREM.CODPROD,
        IREM.VLRUNIT,
        IREM.CODVOL,
        IREM.QTDNEG,
        SUM(NVL(VAR.QTDATENDIDA,0)) QTDRETORNO,
        IREM.CONTROLE,
        IREM.CODLOCALORIG,
        IREM.CODLOCALTERC
    FROM TGFCAB CREM
             INNER JOIN TGFITE IREM ON IREM.NUNOTA = CREM.NUNOTA
             LEFT JOIN TGFVAR VAR ON VAR.NUNOTAORIG = CREM.NUNOTA AND VAR.SEQUENCIAORIG = IREM.SEQUENCIA

    WHERE CREM.NUNOTA IN (SELECT DISTINCT V.NUNOTAORIG FROM TGFCAB C
                                                                INNER JOIN TGFVAR V ON V.NUNOTA = C.NUNOTA

                          WHERE C.NUNOTA = :NUNOTA)

    GROUP BY IREM.NUNOTA,
             IREM.SEQUENCIA,
             IREM.CODPROD,
             IREM.VLRUNIT,
             IREM.CODVOL,
             IREM.QTDNEG,
             IREM.CONTROLE,
             IREM.CODLOCALORIG,
             IREM.CODLOCALTERC)

SELECT
    R.NUNOTAREM,
    R.SEQUENCIAREM,
    R.CODPROD,
    R.VLRUNIT,
    R.CODVOL,
    R.QTDNEG,
    R.QTDRETORNO,
    R.CONTROLE,
    R.QTDNEG - R.QTDRETORNO QTDPENDRET,
    R.CODLOCALORIG,
    R.CODLOCALTERC
FROM RETREM R

WHERE R.QTDNEG - R.QTDRETORNO > 0

