WITH RETREM AS (
    SELECT
        IREM.NUNOTA NUNOTAREM,
        IREM.SEQUENCIA SEQUENCIAREM,
        IREM.CODPROD,
        IREM.VLRUNIT,
        IREM.CODVOL,
        IREM.QTDNEG,
        SUM(NVL(VAR.QTDATENDIDA,0)) QTDRETORNO,
        IREM.CONTROLE,
        IREM.CODLOCALORIG,
        IREM.CODLOCALTERC
    FROM TGFCAB CREM
             INNER JOIN TGFITE IREM ON IREM.NUNOTA = CREM.NUNOTA
             LEFT JOIN TGFVAR VAR ON VAR.NUNOTAORIG = CREM.NUNOTA AND VAR.SEQUENCIAORIG = IREM.SEQUENCIA

    WHERE CREM.NUNOTA IN (SELECT DISTINCT V.NUNOTAORIG FROM TGFCAB C
                                                                INNER JOIN TGFVAR V ON V.NUNOTA = C.NUNOTA

                          WHERE C.TIPMOV = 'D'
                            AND C.NUNOTA = :NUNOTA)

    GROUP BY IREM.NUNOTA,
             IREM.SEQUENCIA,
             IREM.CODPROD,
             IREM.VLRUNIT,
             IREM.CODVOL,
             IREM.QTDNEG,
             IREM.CONTROLE,
             IREM.CODLOCALORIG,
             IREM.CODLOCALTERC

    UNION ALL

    SELECT
        ITE.NUNOTA NUNOTAREM,
        ITE.SEQUENCIA SEQUENCIAREM,
        ITE.CODPROD,
        ITE.VLRUNIT,
        ITE.CODVOL,
        ITE.QTDNEG,
        SUM(NVL(VAR.QTDATENDIDA,0)) QTDRETORNO,
        ITE.CONTROLE,
        ITE.CODLOCALORIG,
        ITE.CODLOCALTERC
    FROM TGFCAB CAB
             INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
             LEFT JOIN TGFVAR VAR ON VAR.NUNOTAORIG = CAB.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA

    WHERE CAB.TIPMOV = 'V'
      AND CAB.NUNOTA = :NUNOTA

    GROUP BY ITE.NUNOTA,
             ITE.SEQUENCIA,
             ITE.CODPROD,
             ITE.VLRUNIT,
             ITE.CODVOL,
             ITE.QTDNEG,
             ITE.CONTROLE,
             ITE.CODLOCALORIG,
             ITE.CODLOCALTERC)

SELECT
    R.NUNOTAREM,
    R.SEQUENCIAREM,
    R.CODPROD,
    R.VLRUNIT,
    R.CODVOL,
    R.QTDNEG,
    R.QTDRETORNO,
    R.CONTROLE,
    R.QTDNEG - R.QTDRETORNO QTDPENDRET,
    R.CODLOCALORIG,
    R.CODLOCALTERC
FROM RETREM R

WHERE R.QTDNEG - R.QTDRETORNO > 0

