SELECT
    CAST(I.CODEMP AS FLOAT) AS CODEMP,
    CAST(EMP.CODLOCALTERC AS FLOAT) AS CODLOCALTERC,
    CAST(I.CODPROD AS FLOAT) AS CODPROD,
    CAST(E.CODLOCAL AS FLOAT) AS CODLOCAL,
    CAST(0 AS FLOAT) AS CODPARC,
    'P' AS TIPO,
    E.CONTROLE,
    ROUND(SUM(CASE WHEN P.USOPROD = 'S' THEN 0 ELSE ((I.QTDNEG)* I.ATUALESTOQUE) END),9) AS CENTRAL,
    ROUND(CAST(E.ESTOQUE AS FLOAT),9) AS ESTOQUE,
    0 AS RESERVADO,
    0 AS OFICIAL,
    1 AS VERIFICACAO
FROM TGFITE I
   , TGFEST E
   , TGFPRO P
   , TGFEMP EMP
WHERE   I.RESERVA = 'N'
  AND E.CODEMP   > 0
  AND EMP.CODEMP = E.CODEMP
  AND E.CODPROD  IN (:CODPROD)
  AND I.CONTROLE  IN (:CONTROLE)
  AND I.CODEMP  = E.CODEMP
  AND I.CODPROD = E.CODPROD
  AND I.CODLOCALORIG = E.CODLOCAL
  AND I.CONTROLE = E.CONTROLE
  AND E.CODPARC = 0
  AND I.NUNOTA >= 0
  AND I.CODPROD = P.CODPROD
  AND I.ATUALESTOQUE <> 0
  AND P.USOPROD <> 'S'

GROUP BY I.CODEMP, EMP.CODLOCALTERC, I.CODPROD, E.CODLOCAL, E.CONTROLE, E.ESTOQUE, P.DECQTD
HAVING  ROUND(ABS(ROUND(SUM(CASE WHEN P.USOPROD = 'S' THEN 0 ELSE ((I.QTDNEG)* I.ATUALESTOQUE) END),9) - ROUND(E.ESTOQUE,9)), 9) >= 0.00001

UNION ALL

SELECT
    CAST(I.CODEMP AS FLOAT) AS CODEMP,
    CAST(EMP.CODLOCALTERC AS FLOAT) AS CODLOCALTERC,
    CAST(I.CODPROD AS FLOAT) AS CODPROD,
    CAST(I.CODLOCALORIG AS FLOAT) AS CODLOCAL,
    CAST(0 AS FLOAT) AS CODPARC,
    'P' AS TIPO,
    I.CONTROLE,
    ROUND(SUM(CASE WHEN P.USOPROD = 'S' THEN 0 ELSE ((I.QTDNEG)* I.ATUALESTOQUE) END),9) AS CENTRAL,
    CAST(0.000000000 AS FLOAT) AS ESTOQUE,
    0 AS RESERVADO,
    0 AS OFICIAL,
    1 AS VERIFICACAO
FROM TGFITE I
   , TGFPRO P
   , TGFEMP EMP
WHERE   I.RESERVA = 'N'
  AND I.CODEMP   > 0
  AND EMP.CODEMP = I.CODEMP
  AND I.CODPROD  IN (:CODPROD)
  AND I.CONTROLE  IN (:CONTROLE)
  AND I.NUNOTA >= 0
  AND I.CODPROD = P.CODPROD
  AND I.ATUALESTOQUE <> 0
  AND P.USOPROD <> 'S'

  AND NOT EXISTS
    (
        SELECT 1 FROM TGFEST E1
        WHERE E1.CODEMP   = I.CODEMP
          AND   E1.CODPROD  = I.CODPROD
          AND   E1.CODLOCAL = I.CODLOCALORIG
          AND   E1.CONTROLE = I.CONTROLE
          AND   E1.CODPARC  = 0
    )
GROUP BY I.CODEMP, EMP.CODLOCALTERC, I.CODPROD, I.CODLOCALORIG, I.CONTROLE, P.DECQTD
HAVING ROUND(SUM(CASE WHEN P.USOPROD = 'S' THEN 0 ELSE ((I.QTDNEG)* I.ATUALESTOQUE) END),9) <> 0



UNION ALL SELECT
              CAST(I.CODEMP AS FLOAT) AS CODEMP,
              CAST(EMP.CODLOCALTERC AS FLOAT) AS CODLOCALTERC,
              CAST(I.CODPROD AS FLOAT) AS CODPROD,
              CAST(E.CODLOCAL AS FLOAT) AS CODLOCAL,
              CAST(E.CODPARC AS  FLOAT) AS CODPARC,
              CASE WHEN I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END AS TIPO,
              E.CONTROLE,
              ROUND(SUM(I.QTDNEG * CASE WHEN I.ATUALESTTERC IN ('P', 'T') THEN 1 ELSE -1 END * CASE WHEN I.SEQUENCIA > 0 THEN 1 ELSE -1 END), 9) AS CENTRAL,
              ROUND(CAST(E.ESTOQUE AS FLOAT), 9) AS ESTOQUE,
              0 AS RESERVADO,
              0 AS OFICIAL,
              1 AS VERIFICACAO
FROM TGFITE I
   , TGFEST E
   , TGFPRO P
   , TGFCAB C
   , TGFTOP T
   , TGFEMP EMP
WHERE   I.RESERVA = 'N'
  AND I.ATUALESTTERC IN ('P','T','R','D')
  AND E.CODEMP   > 0
  AND E.CODPROD  IN (:CODPROD)
  AND I.CONTROLE  IN (:CONTROLE)
  AND I.CODEMP  = E.CODEMP
  AND I.CODEMP = EMP.CODEMP
  AND E.CODEMP = EMP.CODEMP
  AND I.CODPROD = E.CODPROD
  AND CASE when NVL(I.TERCEIROS,'N') = 'N' THEN I.CODLOCALORIG ELSE NVL(I.CODLOCALTERC,I.CODLOCALORIG) END = E.CODLOCAL
  AND I.CONTROLE = E.CONTROLE
  AND I.CONTROLE = E.CONTROLE
  AND I.NUNOTA >= 0
  AND I.CODPROD = P.CODPROD
  AND I.NUNOTA = C.NUNOTA
  AND T.CODTIPOPER = C.CODTIPOPER
  AND T.DHALTER = C.DHTIPOPER
  AND CASE WHEN C.CODPARCDEST <> 0 AND
                I.ATUALESTTERC IN ('P','T') AND
                (NVL(T.CODCFO_ENTRADA,0) IN (1122,2122) OR
                 NVL(T.CODCFO_ENTRADA_FORA,0) IN (1122,2122))
               THEN C.CODPARCDEST
           ELSE C.CODPARC
          END = E.CODPARC
  AND E.TIPO = CASE WHEN I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END


GROUP BY I.CODEMP, EMP.CODLOCALTERC, I.CODPROD, E.CODLOCAL, E.CONTROLE, E.ESTOQUE, E.CODPARC, P.DECQTD, CASE WHEN I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END
HAVING  ROUND(ABS(ROUND(SUM(I.QTDNEG * CASE WHEN I.ATUALESTTERC IN ('P', 'T')  THEN 1 ELSE -1 END * CASE WHEN I.SEQUENCIA > 0 THEN 1 ELSE -1 END),9) - ROUND(E.ESTOQUE,9)),9) > 0.00001

UNION ALL

SELECT
    CAST(I.CODEMP AS FLOAT) AS CODEMP,
    CAST(EMP.CODLOCALTERC AS FLOAT) AS CODLOCALTERC,
    CAST(I.CODPROD AS FLOAT) AS CODPROD,
    CAST(CASE when NVL(I.TERCEIROS,'N') = 'N' THEN I.CODLOCALORIG ELSE NVL(I.CODLOCALTERC,I.CODLOCALORIG) END AS FLOAT) AS CODLOCAL,
    CAST(CASE WHEN C.CODPARCDEST <> 0 AND
                   I.ATUALESTTERC IN ('P','T') AND
                   (NVL(T.CODCFO_ENTRADA,0) IN (1122,2122) OR
                    NVL(T.CODCFO_ENTRADA_FORA,0) IN (1122,2122))
                  THEN C.CODPARCDEST
              ELSE C.CODPARC
        END AS FLOAT) AS CODPARC,
    CASE WHEN I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END AS TIPO,
    I.CONTROLE,
    ROUND(SUM(I.QTDNEG * CASE WHEN I.ATUALESTTERC IN ('P', 'T') THEN 1 ELSE -1 END * CASE WHEN I.SEQUENCIA > 0 THEN 1 ELSE -1 END), 9) AS CENTRAL,
    CAST(0.000000000 AS FLOAT) AS ESTOQUE,
    0 AS RESERVADO,
    0 AS OFICIAL,
    1 AS VERIFICACAO
FROM TGFITE I
   , TGFPRO P
   , TGFCAB C
   , TGFTOP T
   , TGFEMP EMP
WHERE   I.RESERVA = 'N'
  AND I.CODEMP   > 0
  AND I.CODEMP = EMP.CODEMP
  AND I.CODPROD  IN (:CODPROD)
  AND I.CONTROLE  IN (:CONTROLE)
  AND I.NUNOTA >= 0
  AND I.CODPROD = P.CODPROD
  AND I.ATUALESTTERC IN ('P','T','R','D')
  AND I.NUNOTA = C.NUNOTA
  AND T.CODTIPOPER = C.CODTIPOPER
  AND T.DHALTER = C.DHTIPOPER


  AND NOT EXISTS
    (
        SELECT 1 FROM TGFEST E1
        WHERE E1.CODEMP   = I.CODEMP
          AND   E1.CODPROD  = I.CODPROD
          AND   E1.CODLOCAL = CASE when NVL(I.TERCEIROS,'N') = 'N' THEN I.CODLOCALORIG ELSE NVL(I.CODLOCALTERC,I.CODLOCALORIG) END
          AND   E1.CONTROLE = I.CONTROLE
          AND   CASE WHEN C.CODPARCDEST <> 0 AND
                          I.ATUALESTTERC IN ('P','T') AND
                          (NVL(T.CODCFO_ENTRADA,0) IN (1122,2122) OR
                           NVL(T.CODCFO_ENTRADA_FORA,0) IN (1122,2122))
                         THEN C.CODPARCDEST
                     ELSE C.CODPARC
                    END = E1.CODPARC
          AND   E1.TIPO = CASE when I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END
    )
GROUP BY I.CODEMP, EMP.CODLOCALTERC, I.CODPROD, CASE when NVL(I.TERCEIROS,'N') = 'N' THEN I.CODLOCALORIG ELSE NVL(I.CODLOCALTERC,I.CODLOCALORIG) END, I.CONTROLE
       , CASE WHEN C.CODPARCDEST <> 0 AND
                   I.ATUALESTTERC IN ('P','T') AND
                   (NVL(T.CODCFO_ENTRADA,0) IN (1122,2122) OR
                    NVL(T.CODCFO_ENTRADA_FORA,0) IN (1122,2122))
                  THEN C.CODPARCDEST
              ELSE C.CODPARC
    END
       , CASE WHEN I.ATUALESTTERC IN ('T','D') THEN 'T' ELSE 'P' END
HAVING ROUND(SUM(I.QTDNEG * CASE WHEN I.ATUALESTTERC IN ('P', 'T') THEN 1 ELSE -1 END * CASE WHEN I.SEQUENCIA > 0 THEN 1 ELSE -1  END), 9) <> 0