SELECT
    D.DESCRICAO DOCUMENTO
FROM TGFCAB CAB
         INNER JOIN AD_BHZTOPDOC TD ON TD.CODTIPOPER = CAB.CODTIPOPER
         INNER JOIN AD_BHZCADDOC D ON D.CODDOC = TD.CODDOC
         LEFT JOIN TGFCONT A ON A.NUNOTA = CAB.NUNOTA AND A.AD_CODDOC = TD.CODDOC

WHERE CAB.NUNOTA = :NUNOTA
  AND A.AD_ANEXO IS NULL